server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json
  max-http-header-size: 10000000

spring:
  resources:
    chain:
      cache: false
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        hbm2ddl:
          import_files:
            database/initial.sql

  datasource:
    url: jdbc:postgresql://localhost:5432/autenticacao
    username: meutreino
    password: meutreino
    driverClassName: org.postgresql.Driver
    hikari:
      maximumPoolSize: 2
      connectionTestQuery: select 1

app-config:
  oauth-clients:
      front-apps:
        client: app-client
        secret: 4pp
      external-api:
        client: external-api
        secret: 4p1

keys:
    private: 4uthsTr1ng