server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/css,application/javascript,application/json
  max-http-header-size: 10000000

app-config:
  oauth-clients:
      front-apps:
        client: app-client
        secret: 4pp
      external-api:
        client: external-api
        secret: 4p1

keys:
    private: 4uthsTr1ng